import comp from "/Users/nan/code/nan-dome/nan-blogs/.vuepress/.temp/pages/note/Javascript/webgl/container.html.vue"
const data = JSON.parse("{\"path\":\"/note/Javascript/webgl/container.html\",\"title\":\"WebLG 容器（坐标系）\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"WebLG 容器（坐标系）\",\"date\":\"2023-09-08T00:00:00.000Z\",\"order\":-1,\"tag\":[\"Webgl\"],\"category\":[\"Javascript/Typescript\"],\"description\":\"WebLG 容器 在浏览器使用 canvas 作为 weblg 容器 在声明canvas上下文对象时使用 weblg 作为 contextId 坐标系与绘制区间 webgl使用的是正交右手坐标系 切每一个方向可使用的值的区间为0到1 超出该区间的图像不会绘制 x最左边为-1,最右边为1; y轴最下边为-1，最上边为1; z轴朝向你的方向最大值为1，远离...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"WebLG 容器（坐标系）\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-09-08T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"NAN\\\",\\\"url\\\":\\\"https://github.com/open-nan\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://export-nan.github.io/nan-blogs/note/Javascript/webgl/container.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"NAN\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"WebLG 容器（坐标系）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"WebLG 容器 在浏览器使用 canvas 作为 weblg 容器 在声明canvas上下文对象时使用 weblg 作为 contextId 坐标系与绘制区间 webgl使用的是正交右手坐标系 切每一个方向可使用的值的区间为0到1 超出该区间的图像不会绘制 x最左边为-1,最右边为1; y轴最下边为-1，最上边为1; z轴朝向你的方向最大值为1，远离...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Webgl\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-09-08T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":1.24,\"words\":373},\"filePathRelative\":\"note/Javascript/webgl/container.md\",\"excerpt\":\"<h2>WebLG 容器</h2>\\n<p>在浏览器使用 canvas 作为 weblg 容器</p>\\n<div class=\\\"language-html line-numbers-mode\\\" data-highlighter=\\\"shiki\\\" data-ext=\\\"html\\\" style=\\\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\\\"><pre class=\\\"shiki shiki-themes one-light one-dark-pro vp-code\\\"><code class=\\\"language-html\\\"><span class=\\\"line\\\"><span style=\\\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\\\">&lt;</span><span style=\\\"--shiki-light:#E45649;--shiki-dark:#E06C75\\\">canvas</span><span style=\\\"--shiki-light:#986801;--shiki-dark:#D19A66\\\">  id</span><span style=\\\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\\\">=</span><span style=\\\"--shiki-light:#50A14F;--shiki-dark:#98C379\\\">\\\"canvas\\\"</span><span style=\\\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\\\">&gt; &lt;/</span><span style=\\\"--shiki-light:#E45649;--shiki-dark:#E06C75\\\">canvas</span><span style=\\\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\\\">&gt;</span></span></code></pre>\\n<div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\" style=\\\"counter-reset:line-number 0\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
