<template><div><h2 id="问题" tabindex="-1"><a class="header-anchor" href="#问题"><span>问题</span></a></h2>
<p>今天在用 vscode 的 Javascript debug Treminla 调试新项目的时候没办法进入调试状态，我卸载了重装依旧没有办法排除问题<br>
表现为:</p>
<p>对代码</p>
<div class="language-js line-numbers-mode" data-highlighter="shiki" data-ext="js" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-js"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// test.js</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">const</span><span style="--shiki-light:#986801;--shiki-dark:#E5C07B"> a</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">debugger</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">console</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">log</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">a</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>执行</p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">node</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./test.js</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>会直接打印出 <code v-pre>1</code> 而不会进入调试状态</p>
<h2 id="排查" tabindex="-1"><a class="header-anchor" href="#排查"><span>排查</span></a></h2>
<p>先掉用 <code v-pre>node --inspect-brk ./test.js</code> 然后打开 chrome 浏览器，输入 <code v-pre>chrome://inspect</code>，发现调试正常，说明是 vscode 的问题</p>
<p>直接在 vscode 的 Javascript debug Treminla 中运行<code v-pre>node -e  'debugger;console.log('hit');'</code>, 发现打印出 <code v-pre>hit</code>，没有进入调试状态，定位为 vscode 的 Javascript debug Treminla 无法连接到 node 的调试端口, 去翻阅 vscode 的 debug 配置文件，发现 其中有提到它是通过在环境变量中将NODE_OPTIONS指向一个vscode的调试脚本，然后通过这个脚本实现了调试功能，但是这个脚本似乎有问题，导致无法连接到 node 的调试端口</p>
<p>先看看现在的环境是怎么样的</p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">grep</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NODE</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> </span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">> </span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">NODE_OPTIONS</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> --require</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "/Users/nan/Library/Application Support/Code/User/workspaceStorage/74f21fa01b970c11113dd6ef2de0c1ea/ms-vscode.js-debug/bootloader.js"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">  --require</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.js"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">  --inspect-publish-uid=http</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">VSCODE_GIT_ASKPASS_NODE</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">/Applications/Visual</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> Studio</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Code.app/Contents/Frameworks/Code</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Helper</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (Plugin).app/Contents/MacOS/Code Helper (</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Plugin</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这里可以看到，NODE_OPTIONS指向了两个文件，前面这个很明显是一个跟随项目的缓存文件，由于我不同的项目之间有点可以调试，有的不可以调试，于是将可调试的项目对于的这个文件内容覆盖到不可调试的项目文件上，然后重启 vscode，发现可以调试了，确定为这个文件损坏导致的</p>
<p>于是我清空所有的文件</p>
<div class="language-sh line-numbers-mode" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-sh"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">rm</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -rf</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "/Users/nan/Library/Application Support/Code/User/workspaceStorage/"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


